spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email
    stream:
      bindings:
        email-in-0:
          destination: send-communication
          group: ${spring.application.name}
        email-out-0:
          destination: communication-sent
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      connection-timeout: 10s